# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require "base64"
require "json"
default_platform(:ios)

platform :ios do
  desc "Init and download metadata"
  lane :deliver_init do
    api_key = app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_ISSUER_ID"],
      key_content: Base64.decode64(ENV["API_KEY_CONTENT"])
    )

    File.open("/tmp/ios_api_token.json", "w") do |f|
      f.write(api_key.to_json)
    end

    sh("bundle exec fastlane deliver init --api_key_path /tmp/ios_api_token.json -a com.bgra572.himnario")

    File.delete("/tmp/ios_api_token.json")
  end

  desc "Upload new metadata to the App Store"
  lane :deliver_metadata do
    app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_ISSUER_ID"],
      key_content: Base64.decode64(ENV["API_KEY_CONTENT"])
    )

    deliver(
      force: true,
      run_precheck_before_submit: false
    )
  end
end
